version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: unless-stopped

  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    volumes:
      - database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: unless-stopped

volumes:
  database:
    name: database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/database
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/wordpress

networks:
  inception:
    name: inception
    driver: bridge