version: '3.9'

services:
  nginx:
    container_name: inception-nginx
    image: inception-nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    volumes:
      - inception-files:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    restart: on-failure

  mariadb:
    container_name: inception-mariadb
    image: inception-mariadb
    build: ./requirements/mariadb/
    volumes:
      - inception-database:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

  wordpress:
    container_name: inception-wordpress
    image: inception-wordpress
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    volumes:
      - inception-files:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: on-failure

volumes:
  inception-database:
    name: inception-database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/inception-database
  inception-files:
    name: inception-files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/inception-files

networks:
  inception:
    driver: bridge